### ISSUE TITLE
조직도 차트 추가

### ISSUE THREAD

**Issue by mozodev** [team-durumi/hugo-marketing#1]
https://ywca100.vercel.app/about-aniversary

한국YWCA 100주년 준비단 조직도
위 준비단 조직도를 바탕으로 조금 더 예쁜 디자인의 일러 작업으로 해당 칸 요청드립니다. 

https://docs.google.com/presentation/d/1RaoUegXRWniAAhiTFnwOLRhCxrifWMVS/edit#slide=id.p8

이거 그냥 일러로 그리는게 낫지 않을까요? 
켄짱 알바 문의해봐야겠... ㅎ

**Comment by woonjjang** [comment]
일러로 가시죠. 사무국에 계시면 요청을 ~
