### ISSUE TITLE
media query breakpoint 관련 고민

### ISSUE THREAD

**Issue by suncrud** [team-durumi/hugo-marketing#14]
kctu-photo 작업을 하는 와중에 tailwind.config 를 만지다가 media query breakpoint에 대한 고민을 하게 되었습니다. 

일단 tailwind default breakpoint는 아래와 같음:
```
# https://tailwindcss.com/docs/screens
module.exports = {
  theme: {
    screens: {
      'sm': '640px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1280px',
      // => @media (min-width: 1280px) { ... }

      '2xl': '1536px',
      // => @media (min-width: 1536px) { ... }
    }
  }
}
```
그런데 kctu 작업을 하다보니까 (정확히는 그 포토갤러리 너비 사수하다가) max-width로 구분하는게 어떨까 하는 생각이 들었는데요, 

min-width의 경우에는 하한선을 정해놓고 그거보다 더 큰 범위에 대해 각각 media query를 먹이는 거라서 media query 먹이지 않는 디폴트 css 값 같은 경우에는 가장 폭이 좁은 모바일을 염두해두고 만들게 되고 

max-width의 경우에는 반대로 media query마다 너비 상한선을 정해두고 그 미만 너비에 대해 media query를 먹이는거라서 default 값은 너비가 큰 스크린에 적용하고 media query는 폭이 점점 좁아지는 상황에 대응하는 것 같습니다.

저는 돌이켜보면 후자를 많이 상정하고 작업을 했던거 같은데요, 약간 우리 팀 컨벤션에 대해 이야기 한 적은 없는거 같아서 뭔가 어쨌든 현재로서는 혼재되어있는거 같아요 (이건 저의 불찰일지도) 

제 의견은 roll이 아카이브라면 mobile first를 염두하고 만드는게 아니라 너비가 큰 화면을 상정하고 max-width로 가는게 맞는거 같다는 생각이 듭니다. 

근데 또 default를 오버라이드 하면 나중에 외부에서 컴포넌트 가져올때 일일히 미디어쿼리 바꿔줘야 하는 상황이 생겨서(?) 애를 먹지 않을까 하는 생각이 또 들어서 @woonjjang @mozodev 두분 의견 한번 듣고 싶습니다.

**Comment by mozodev** [comment]
https://stackoverflow.com/a/24640497

mobile first: min-width
desktop first: max-width

지금까지 작업 경험으로는 두루미는 desktop first. 
옛날 사람이나 고인물 조직이 계속 고객이 되면 당연히 계속 이 방향으로 갈 듯 ㅎ
