### ISSUE TITLE
사업 목록 왼쪽으로 치우쳐 보이는 부분 -> 활동소식 partial /메인 

### ISSUE THREAD

**Issue by mozodev** [team-durumi/hugo-marketing#4]
??

**Comment by woonjjang** [comment]
card.html 파샬이 정렬이 안 되는 문제가 있었어요. 
메인 사업 소개 부분(푸터 바로위)에 2개 이미지+버튼 들어가 있는데, 사업내용 뿌려주는 것으로 제안했는데 거절.
그냥 원래대로 활동소식 / 관련자료 를 넣어달라(는 고객의 요청)
